name: orbital
version: 0.0.1.0
github: "vaclavsvejcar/orbital"
license: BSD3
author: Vaclav Svejcar
maintainer: vaclav.svejcar@gmail.com
copyright: 2021 Vaclav Svejcar

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/vaclavsvejcar/orbital#readme>

ghc-options:
  - -optP-Wno-nonportable-include-path

dependencies:
  - base >= 4.7 && < 5
  - rio

library:
  source-dirs: src
  dependencies:
    - conduit
    - cryptonite
    - memory

executables:
  orbital:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - orbital

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cryptonite
      - hspec
      - orbital
    build-tools: hspec-discover
